kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: letsencrypt-certificates-cronjob
  namespace: letsencrypt-job
spec:
  schedule: '0 0 28 */3 *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: hello
              image: "image-registry.openshift-image-registry.svc:5000/letsencrypt-job/oc-acme:latest"
              env:
                - name: STAGING
                  value: 'false'
                - name: PATCH_API_SERVER
                  value: 'true'
              envFrom:
                - secretRef:
                   name: cloud-dns-credentials
              command:
                - /bin/bash
                - -c
                - |
                  #!/usr/bin/env bash
                  
                  /scripts/aws.sh
                  
                  echo "Done!"

              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
          serviceAccount: letsencrypt-job-sa
          erviceAccountName: letsencrypt-job-sa
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
