apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-certificates-job
  namespace: letsencrypt-job
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/letsencrypt-job/ocp-acm:latest
          env:
            - name: STAGING
              value: 'false'
            - name: PATCH_API_SERVER
              value: 'true'
          envFrom:
            - secretRef:
                name: cloud-dns-credentials
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              /scripts/aws.sh

              echo "Done!"

          imagePullPolicy: Always
          name: letsencrypt-certificates-job
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: letsencrypt-job-sa
      serviceAccountName: letsencrypt-job-sa
      terminationGracePeriodSeconds: 30
